### PR TITLE
[ADD][8.0] l10n_id_taxform

### PR DESCRIPTION
**Pull request by andhit-r**
# 
# Indonesia's Taxform

This is the base module for all indonesia's related taxform modules.
Alone this module does nothing other than create root menu

### CODE REVIEW

**Comment by raditv** [comment]
👍

**Comment by andhit-r** [comment]
Close to rebuild travis

**Comment by andhit-r** [comment]
Close to rebuild travis

**Comment by andhit-r** [comment]
Close to rebuild travis

**Comment by andhit-r** [comment]
@mikevhe18 @azmimr67 @primeforcindo please review here also. Many thanks

**Comment by mikevhe18** [comment]
:+1:

**Comment by andhit-r** [comment]
Hi @azmimr67 @primeforcindo would you give reviews and approval on this PR. Many thanks before.

**Comment by andhit-r** [comment]
@OCA/core-maintainers this PR need one more vote from PSC. If someone has time to spare would you kindly give technical review to this PR. Many thanks in advance

**Comment by dreispt** [comment]
I see two approval, that should be enough.
Looking at the code a couple of things raised me some questions:

The module is quite empty - it adds no actual feature other than a top level menu and security groups. Should it provide some basic features?
The menu items provided do nothing, since they don't trigger any Action.
Shouldn't the menus be under Accounting, and shouldn't it have an Accounting dependency?

**Comment by andhit-r** [comment]
@dreispt thanks for your review. This module only (1) add root menu for later taxform modules, and (2) This module also provide groups for later used by another modules. It's like **partner_contact_personal_information_page** module which only provide empty page for later personal information modules. 

It does not depend on account module, because it does not need it yet. Later taxform modules might depend on account module. Also, i want different root menu for taxform, not under Accounting root menu. So no need to depend to account yet.

**Comment by dreispt** [comment]
Why do you want a new top menu? Is this Tax feature designed to be independent from Accounting? Because Accounting already adds the Vat field to Partners, as you are doing here.

**Comment by andhit-r** [comment]
@dreispt , bellow my answer to your concerns

## New Top Menu

I need new top menu because (1) complete indonesia taxform feature will be needed a lot of menu. New root menu will avoid over-crowded on Accounting root menu. Here are all the menus that will be created:
- Taxform
  - SPT Tahunan Badan
    - Taxform 1771
  - SPT Tahunan Pribadi
    - Taxform 1770
    - Taxform 1770 S
    - Taxform 1770 SS
  - SPT Masa
    - SPT Masa PPh Art. 21/26
    - SPT Masa PPn Pengkreditan PM
    - SPT Masa PPn 
    - SPT Masa PPnBM Bukan Pemungut
    - SPT Masa PPnBM Pemungut
    - SPT Masa PPh Art. 15
    - SPT Masa PPh Art. 22
    - SPT Masa PPh Art. 23/36
    - SPT Masa PPh Art 4(2)
    - SPT Masa PPn Bukan Pemungut
    - SPT Masa PPn Pemungut
    - SKP and STP
      - STP PPn
      - SKPKB PPn
      - SKPKB PPnBM
      - STP PPnBM
  - Configuration
    - Tax Period
    - PPh
      - ...
      - ...

and (2) in Indonesia, usually people who manage all these taxform different from finance accounting people. So it will be more easier to manage it's security group if it has different root menus.

## Dependency to Accounting Module

Yes taxform will be dependent to accounting modules. But this module not yet need to depend to account module. Other taxform modules might depend to account.

**vat** field exist on **base** module not on **account** module. I only show this field on partner form because no other module show this field.

**Comment by dreispt** [comment]
Thank you for the thorough explanation.
I'm OK with the top menu.
Regarding the Vat field, I'm concerned about having the field twice on the Partner form once you install the Accounting app, since it adds an Accounting tab on Partners including that same field.

**Comment by andhit-r** [comment]
@dreispt i add account as dependency. My mistake, i had really really old odoo branch. It does not have vat field on partner form. Thanks for questioning that.

**Review by dreispt — APPROVED** [review]
Great! Thanks for all the patience and explanations.

**Pull request merged**
