### PR TITLE
[ADD][8.0] l10n_id_taxform_pph_21

### PR DESCRIPTION
**Pull request by andhit-r**
# 
# Indonesia's PPh 21 Taxform Related Configuration and Computation

This module provide configurations and computation that related to
Indonesia's income tax article 21.

Available configurations:
1. Penghasilan Tidak Kena Pajak (PTKP)
2. Biaya Jabatan
3. PPh 21 NPWP Rate Modifier
4. PPh 21 Rate for objek pajak 21-100-01 and 21-100-02

Available computation:
1. PPh 21 for objek pajak 21-100-01 and 21-100-02

All the computations will be used by another modules that needed the
computations.
# Usage

**PTKP Categories**

To manage PTKP categories, you need to:
1. Go to menu _Taxform -> Configuration -> PPh 21 -> PTKP Category_

**PTKP Rates**

To manage PTKP rates, you need to:
1. Go to menu _Taxform -> Configuration -> PPh 21 -> PTKP Rates_

**Biaya Jabatan**

To manage Biaya Jabatan, you need to:
1. Go to menu _Taxform -> Configuration -> PPh 21 -> Biaya Jabatan_

**Non-NPWP Rate Modifiers**

To manage Non-NPWP Rate Modifiers, you need to:
1. Go to menu _Taxform -> Configuration -> PPh 21 -> Non-NPWP Rate Modifiers_

**PPh 21 Rates**

To manage PPh 21 Rates, you need to:
1. Go to menu _Taxform -> Configuration -> PPh 21 -> PPh 21 Rates_

### CODE REVIEW

**Comment by andhit-r** [comment]
@mikevhe18 @azmimr67 @m-sani @sandriandriana would you kindly review this PR. Many thanks.

**Comment by mikevhe18** [comment]
:+1:

**Comment by sandriandriana** [comment]
:+1:

**Comment by m-sani** [comment]
👍

**Comment by azmimr67** [comment]
:+1: function has been tested

**Pull request merged**
